---
- hosts: LAB-VM01
  become: yes
  become_user: root
  vars:
    jenkinsjobname: lab01
    jenkinsclipath: /usr/bin/jenkins-cli.jar
    jenkinstoken: /var/lib/jenkins/secrets/initialAdminPassword
    jenkinsweburl: http://localhost:8080/
    key: "{{ lookup('file', '~/.ansible/files/initialAdminPassword/LAB-VM01/var/lib/jenkins/secrets/initialAdminPassword') }}"
  tasks:
    - name: Check Epel-Release installed
      yum:
        name: epel-release
        state: present
        update_cache: true
    - name: Check Pre-packages installed
      yum:
        name: '{{ prepackages }}'
        state: present
        update_cache: true
      vars:
        prepackages:
          - sshpass
          - daemonize
    - name: Check Jenkins repository is added
      yum_repository:
        name: jenkins-ci
        description: jenkins-ci package repository
        baseurl: http://pkg.jenkins.io/redhat
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        gpgcheck: yes
    - name: Check Jenkins gpp key is imported
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
    - name: Check Jenkins package installed
      yum:
        name: '{{ packages }}'
        state: present
        update_cache: true
      vars:
        packages:
          - java-devel
          - jenkins
    - name: Check systemd daemon reloaded
      ansible.builtin.systemd:
        daemon_reexec: yes
    - name: Check Jenkins service is started
      service:
        name: jenkins
        state: started
    - name: Check Jenkins service added to firewalld
      firewalld:
        service: jenkins
        state: enabled
        permanent: yes
        immediate: yes
    - name: Check port 8080 added to firewalld
      firewalld:
        port: 8080/tcp
        state: enabled
        permanent: yes
        immediate: yes
    - name: Wait for create Jenkins Web Admin token
      wait_for:
        path: "{{ jenkinstoken }}"
    - name: Fetch Web Admin token
      ansible.builtin.fetch:
        dest: ~/.ansible/files/initialAdminPassword
        src: "{{ jenkinstoken }}"
    - name: Transfer job file to Jenkins
      ansible.builtin.copy:
        dest: /etc/lab01.xml
        src: ~/.ansible/files/lab01.xml
    - name: Wait for Jenkins start
      wait_for:
        host=localhost
        port=8080
        delay=60
        timeout=300
    - name: Get Jenkins-cli
      get_url:
        dest: "{{ jenkinsclipath }}"
        url: "{{ jenkinsweburl }}jnlpJars/jenkins-cli.jar"
    - name: Import Job to jenkins
      shell: "java -jar {{ jenkinsclipath }} -s {{ jenkinsweburl }} -auth admin:{{ key }} create-job lab01 < /etc/{{ jenkinsjobname }}.xml"
    - name: Run Jenkins job
      shell: "java -jar {{ jenkinsclipath }} -s {{ jenkinsweburl }} -auth admin:{{ key }} build {{ jenkinsjobname }}"
